apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
## these are replicaset labels
  labels:
    purpose: rs-demo
    project: roboshop
spec:
  replicas: 3
  selector:
  ## these labels sre used to select the pods
    matchLabels:
      purpose: rs-demo
      project: roboshop
  
### pod definition
  template:
    metadata:
      labels:
        purpose: rs-demo
        project: roboshop
    
    spec:
      containers:
      - name: nginx
        image: nginx